### ISSUE TITLE
Library not available in R 4.0

### ISSUE THREAD

**Issue by wabee** [trr266/tidycovid19#15]
After upgrading to R 4.0 I cannot run my scripts on the Corona pandemic. The library is not available for install. Please fix

**Comment by turzes** [comment]
Hi Joachim- thanks for your excellent work- I ran the package last week and it worked perfectly- wonderful - upgraded to R4.0.0 and now I get this error
remotes::install_github("joachim-gassen/tidycovid19")
Downloading GitHub repo joachim-gassen/tidycovid19@master
Error: Failed to install 'tidycovid19' from GitHub:
  lazy-load database '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/pkgbuild/R/pkgbuild.rdb' is corrupt
In addition: Warning messages:
1: In get0(oNam, envir = ns) : restarting interrupted promise evaluation
2: In get0(oNam, envir = ns) : internal error -3 in R_decompress1

would be great if you could help resolve if possible,
many thanks,
Mark

**Comment by turzes** [comment]
Just to add to previous mail- I am on an IMAC running catalina 10.15.4
thanks,
Mark

**Comment by einarhjorleifsson** [comment]
@turzes: the message implies that there is some problem with {pkgbuild}
if that is a correct hunch, solve that first.
einar

**Comment by joachim-gassen** [comment]
Apologies for the delay and I am not sure who is still struggling with this issue but I tested the package in an R 4.0 container (further info on how [here](https://joachim-gassen.github.io/2020/05/checking-your-package-for-compatibility-with-r-4/) in case you are interested) and it works. So, like also indicated by others above, {tidycovid19} is most likely not the issue here.
