### ISSUE TITLE
Date parse error when using download_google_trends_data()

### ISSUE THREAD

**Issue by conrad-mac** [trr266/tidycovid19#2]
Hi again,

I get `Error: Cannot parse the supplied time format.` when running `download_google_trends_data("coronavirus")`. I'm in New Zealand so it is already April 1 here. I think this is outside the time window for google trends at the moment. 

I would suggest changing `time <- paste("2020-01-01", Sys.Date())` to something like `time <- paste("2020-01-01", lubridate::today(tzone = "Europe/Berlin"))` or whichever timezone makes sense.

Cheers

**Comment by joachim-gassen** [comment]
Hi there: Now this was a funny one. I switched to US/Pacific but am unsure whether this fixes it completely. Maybe it would be better to err on the side of caution by stopping one day earlier. Thus, I leave the issue open for the time being. Thanks!

**Comment by harun2842** [comment]
Hi, Thanks for developing this nice app. I like it. How can I change the default country list for the plots? For example, I like to add Australia. How can I do it?

Also having trouble to run-

load("shiny_data.Rda")
-cannot open compressed file 'shiny_data.Rda', probable reason 'No such file or directory'

but if I replace that with-

shiny_data <- download_merged_data(silent = TRUE, cached = TRUE)

then the app runs without any error.

<img width="1247" alt="Screen Shot 2020-04-10 at 12 57 44 pm" src="https://user-images.githubusercontent.com/15321172/78958321-11c2a300-7b2b-11ea-8771-5361a6163c27.png">

**Comment by joachim-gassen** [comment]
Hi, there and thank you. Four things related to your post:

- The reason that you do not see Australia in the drop down list of the screenshot is that it has less than 100 deaths. If you reduce the number of cases to mark day zero to 10, Australia will pop up.
- Related to that, I just added an option to the `shiny_covid19_spread()` function call allowing you to add default options as a list to the parameter `plot_options`. So, to start the app with a plot highlighting Australia you would do something like
```
remotes::install_github("joachim-gassen/tidycovid19") # to get the new version
library(tidycovid19)
shiny_covid19_spread(plot_options = list(
  min_cases = 10, highlight = c("AUS"))
)
```
- The error message that you mention seems to indicate that you tried running the file `app.R` from the package directory instead of calling the function `shiny_covid19_spread()`. The app relies on a temporary directory structure to be present that the function `shiny_covid19_spread()` sets up and is not meant to be called directly. 
- Next time, please do not 'hi-jack' an issue on an unrelated topic when asking your question. Instead open up a new issue if your question does not clearly relate to an existing issue. I am closing this issue now as its original topic seems to be settled.
