### ISSUE TITLE
Error downloading world bank data

### ISSUE THREAD

**Issue by alexandrsanches** [trr266/tidycovid19#23]
I was using ```download_merged_data(cached = TRUE)``` and today I realized that there was one less variable (gdp_capita). Trying to use ```download_wbank_data()```it returns the following error:

![Captura de Tela 2020-05-21 às 09 29 24](https://user-images.githubusercontent.com/55547524/82559210-94d11300-9b45-11ea-9a98-91ba25e9302e.png)

**Comment by joachim-gassen** [comment]
Thanks for the heads up! It appears that there has been an issue with the World Bank download yesterday. It should be fixed in todays upload. As I would be interested in identifying the underlying cause: Could you please check whether you can now download worldbank data using `download_wbank_data()` ? And, if this is not the case, verify that you are running the newest version of the `wbstat` package? And then, if you still receive an error, send me the (translated) error message? That would be super.

**Comment by alexandrsanches** [comment]
I just updated the ```wbstat``` package e try again ```download_wbank_data()```, but, it returned the same error. I'm sorry I forgot to translate the error.

```
Start downloading World Bank data

Error in call_api(url_string = url_string, indicator = indicator) : 
  argument "indicator" is missing, no pattern
```

**Comment by joachim-gassen** [comment]
Hi there! Sorry for the delay. I am still not able to reproduce this one. Can you please verify that you are using the current version of the package by running:

```packageDescription("tidycovid19", field = "GithubSHA1")```

It returns the SHA of your install. The current version as of the morning of June 6 is 

```016fede43ae5e49b592744d8e108830aaf77303d```

If you are running an old version, please update: 

```remotes::install_github("joachim-gassen/tidycovid19")```

Then restart R and try to download Worldbank data 

```wbank_df <- download_wbank_data()```

If it does not work please run

```
traceback()
rlang::last_error()
sessionInfo()
```

and post the output here. This would help me to trace down the issue.

Thanks!

**Comment by alexandrsanches** [comment]
Hi! Thank you for you patience. I tried today and it worked.

Now, when I download World Bank data, the function works perfectly.
