### ISSUE TITLE
Error using download_oxford_npi_data()

### ISSUE THREAD

**Issue by rivaldophilip** [trr266/tidycovid19#25]
The Oxford COVID-19 Government Response Tracker (OxCGRT) changed its variables and variable names so the function is not working anymore. Hope that there will be an update! Thank you.

**Comment by joachim-gassen** [comment]
Thank you for the heads up. It seems as if the Oxford team has changed the data structure again so that the code now runs through. Can you verify that it works again for you as well?

**Comment by rivaldophilip** [comment]
I still having trouble running the function. It just returns:

Start downloading Oxford NPI data

Error: Column `LegacyStringencyIndex` not found in `.data`

**Comment by joachim-gassen** [comment]
Hi there! This indicates that you are running an old version of the package as this field is no longer referenced in the current version of the code. Can you run 
`packageDescription("tidycovid19", field = "GithubSHA1")`? It returns the SHA of your install. The current version as of the morning of June 6 is `016fede43ae5e49b592744d8e108830aaf77303d`.

If you are running an old version, simply update `remotes::install_github("joachim-gassen/tidycovid19")` and check whether the download now works for you.

Thanks for letting me know so that I can close the issue if everything is settled.

**Comment by rivaldophilip** [comment]
Thank you so much! It works now. Reinstalling the package and restarting R did the trick.
